import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./fonts/fonts";
import { AuthProvider } from "./context/authContext";
import { CartProvider } from "./context/cartContext";

export const metadata: Metadata = {
  title: "Little Tokyo Sushi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={poppins.className}>
        <AuthProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
